---
- name: Install Nginx on multiple nodes
  hosts: all
  become: yes  # Use 'become' to run tasks as a privileged user
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
