- name: Test connectivity
  hosts: all
  tasks:
    - name: Ping target machines
      ansible.builtin.ping:
- import_playbook: send-status-to-cent.yml
  vars:
    service_description: "My Service"
    state: "OK"
    output: "Job completed successfully"
