---
- name: Send job status to Centreon via NSCA
  hosts: localhost
  gather_facts: true
  vars:
    centreon_host: "3.107.195.71"
    nsca_port: 5667
    service: "AWX Job Status"
    hostname: "{{ ansible_hostname }}"
    status_code: "{{ '0' if job_result == 'success' else '2' }}"
    message: "AWX Job '{{ job_name }}' completed with status '{{ job_result }}'"

  tasks:
    - name: Create NSCA input line
      copy:
        content: "{{ hostname }}\t{{ service }}\t{{ status_code }}\t{{ message }}\n"
        dest: "/tmp/nsca_input.txt"

    - name: Send status using send_nsca
      command: >
        send_nsca -H {{ centreon_host }} -p {{ nsca_port }}
        -c /var/lib/awx/projects/_8__abhishek_test_project/send_nsca.cfg
        < /tmp/nsca_input.txt
