---
- name: Send job status to Centreon via NSCA
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create NSCA input line
      ansible.builtin.copy:
        dest: /tmp/nsca_input.txt
        content: "{{ centreon_host_name }}\t{{ centreon_service }}\t{{ job_status }}\n"
        mode: '0644'

    - name: Send status to Centreon server using send_nsca
      ansible.builtin.shell: >
        send_nsca -H {{ centreon_server_ip }} -c /etc/send_nsca.cfg < /tmp/nsca_input.txt
      become: no
