---
- name: Send job status to Centreon via NSCA
  hosts: localhost
  gather_facts: false
  vars:
    # Map job_status/state string to NSCA return code
    nsca_return_code_map:
      OK: 0
      WARNING: 1
      CRITICAL: 2
      UNKNOWN: 3

  tasks:
    - name: Determine NSCA return code
      set_fact:
        nsca_return_code: "{{ nsca_return_code_map[state | upper] | default(3) }}"

    - name: Create NSCA input file
      ansible.builtin.copy:
        dest: /tmp/nsca_input.txt
        content: "{{ inventory_hostname }}\t{{ service_description }}\t{{ nsca_return_code }}\t{{ output }}\n"
        mode: '0644'

    - name: Send status to Centreon server using send_nsca
      ansible.builtin.command: >
        send_nsca -H {{ lookup('env', 'CENTREON_IP') }} -c /etc/send_nsca.cfg < /tmp/nsca_input.txt
      register: send_nsca_result
      failed_when: send_nsca_result.rc != 0
      changed_when: false

    - name: Debug send_nsca output
      ansible.builtin.debug:
        var: send_nsca_result.stdout
