---
- name: Send job status to Centreon via NSCA
  hosts: localhost
  gather_facts: false
  vars:
    nsca_message: "{{ inventory_hostname }}\tJob_Status\t0\tJob completed successfully"
  tasks:
    - name: Create NSCA input line
      copy:
        dest: /tmp/nsca_input.txt
        content: "{{ nsca_message }}"

    - name: Send status to Centreon NSCA server
      command: >
        /usr/sbin/send_nsca -H {{ centreon_server_ip }} -c /etc/send_nsca.cfg < /tmp/nsca_input.txt
