---
- name: Verify send_nsca presence
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if send_nsca exists
      ansible.builtin.stat:
        path: /usr/sbin/send_nsca
      register: send_nsca_stat

    - name: Print send_nsca presence
      debug:
        msg: "send_nsca is present at /usr/sbin/send_nsca"
      when: send_nsca_stat.stat.exists

    - name: Fail if send_nsca is not present
      fail:
        msg: "send_nsca is NOT present in this Execution Environment!"
      when: not send_nsca_stat.stat.exists
