---
- name: Verify send_nsca presence
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if send_nsca exists at /usr/sbin/send_nsca
      stat:
        path: /usr/sbin/send_nsca
      register: send_nsca_stat

    - name: Print send_nsca existence
      debug:
        var: send_nsca_stat.stat.exists

    - name: Show send_nsca help output
      command: /usr/sbin/send_nsca --help
      register: send_nsca_help
      ignore_errors: yes

    - name: Print send_nsca help output
      debug:
        var: send_nsca_help.stdout
